#ifndef SOURCES_LIBMODBUSWRAPPER_INCLUDE_MODBUSWRAPPERS_EXPORT_H_
#define SOURCES_LIBMODBUSWRAPPER_INCLUDE_MODBUSWRAPPERS_EXPORT_H_

#ifndef MODBUSWRAPPERS_STATIC_DEFINE

#  include <modbuswrappers/export_shared.h>
#else
#  include <modbuswrappers/export_static.h>
#endif

#endif //SOURCES_LIBMODBUSWRAPPER_INCLUDE_MODBUSWRAPPERS_EXPORT_H_
