#ifndef CPP_PROJECT_TEMPLATE_MVC_DEVICE_CONTROLLERS_DEVICECONTROLLER_H_
#define CPP_PROJECT_TEMPLATE_MVC_DEVICE_CONTROLLERS_DEVICECONTROLLER_H_

#include <QObject>


class DeviceController: public QObject {

};

#endif //CPP_PROJECT_TEMPLATE_MVC_DEVICE_CONTROLLERS_DEVICECONTROLLER_H_
