#ifndef MODBUSWRAPPERS_LIBMODBUSWRAPPER_INCLUDE_MODBUSWRAPPERS_MODBUSASYNCCLIENTWRAPPER_ABSTRACTMODBUSASYNCCLIENTWRAPPER_H_
#define MODBUSWRAPPERS_LIBMODBUSWRAPPER_INCLUDE_MODBUSWRAPPERS_MODBUSASYNCCLIENTWRAPPER_ABSTRACTMODBUSASYNCCLIENTWRAPPER_H_

#include "modbuswrappers/modbuswrapper.h"


class AbstractModbusAsyncClientWrapper: public ModbusWrapper {
 public:
  virtual const std::vector<uint16_t> &getHoldingRegs() = 0;
  virtual const std::vector<uint16_t> &getInputRegs() = 0;
};

#endif //MODBUSWRAPPERS_LIBMODBUSWRAPPER_INCLUDE_MODBUSWRAPPERS_MODBUSASYNCCLIENTWRAPPER_ABSTRACTMODBUSASYNCCLIENTWRAPPER_H_
