#ifndef TEST_PROJECT_WITH_MODULE_ARCH_THREADPOOLING_IPROCESSABLE_H_
#define TEST_PROJECT_WITH_MODULE_ARCH_THREADPOOLING_IPROCESSABLE_H_


class IProcessable {
 public:
  virtual void process() = 0;
};

#endif //TEST_PROJECT_WITH_MODULE_ARCH_THREADPOOLING_IPROCESSABLE_H_
