#ifndef TEST_PROJECT_WITH_MODULE_ARCH_SERVICES_MODELS_IMPLS_STANDALONEIMPL_BACKGROUND_PERIODICTASK_H_
#define TEST_PROJECT_WITH_MODULE_ARCH_SERVICES_MODELS_IMPLS_STANDALONEIMPL_BACKGROUND_PERIODICTASK_H_

#include "threadpooling/iprocessable.h"


class ThreadPoolTask: public IProcessable {
 public:
  virtual void setBusy(bool busy) = 0;
  virtual bool isReady() = 0;
};

#endif //TEST_PROJECT_WITH_MODULE_ARCH_SERVICES_MODELS_IMPLS_STANDALONEIMPL_BACKGROUND_PERIODICTASK_H_
